### ISSUE TITLE
Youtube .net library: Set HttpWebRequest.Timeout to prevent error "The request was aborted: The request was canceled."

### ISSUE THREAD

**Issue by GoogleCodeExporter** [barsu8184/google-gdata#140]
```
What steps will reproduce the problem?
1. When uploading videos to YouTube via the .Net API, requests can timeout
even though they are active. In our case, attempting to upload files >
~14MB on a contended 2MB synchronous line causes the following exception:

Unhandled Exception: System.Net.WebException: The request was aborted: The
request was canceled.
   at System.Net.ConnectStream.InternalWrite(Boolean async, Byte[] buffer,
Int32 offset, Int32 size, AsyncCallback callback, Object state)
   at System.Net.ConnectStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at Google.GData.Client.GDataGAuthRequest.CopyRequestData()
   at Google.GData.Client.GDataGAuthRequest.Execute(Int32 retryCounter)
   at Google.GData.Client.GDataGAuthRequest.Execute()
   at Google.GData.Client.MediaService.EntrySend(Uri feedUri, AtomBase
baseEntry, GDataRequestType type)
   at Google.GData.Client.Service.Insert(Uri feedUri, AtomEntry newEntry)
   at Google.GData.YouTube.YouTubeService.Upload(YouTubeEntry entry)

The issue can be corrected by adding the following - or something similar -
at line 484 (version 1.2.0.0) of core/request.cs:

if (this.webRequest is HttpWebRequest)
    ((HttpWebRequest)this.webRequest).Timeout = Timeout.Infinite;
```

Original issue reported on code.google.com by `acaz...@gmail.com` on 26 Jun 2008 at 8:43

**Comment by GoogleCodeExporter** [comment]
```
The request factory object has a timeout property. So you can set this from the 
outside to suit your applications 
need. Isn't that sufficient? 
```

Original comment by `fman...@gmail.com` on 28 Jun 2008 at 12:27
- Changed state: **Reviewed**
- Added labels: **Type-Other**
- Removed labels: **Type-Defect**

**Comment by GoogleCodeExporter** [comment]
```
using the timeout property should fix this. 
```

Original comment by `fman...@gmail.com` on 9 Jul 2008 at 1:54
- Changed state: **ByDesign**

**Comment by GoogleCodeExporter** [comment]
```
yes, i do that:

DirectCast(service.RequestFactory, GDataRequestFactory).Timeout =
DirectCast(service.RequestFactory, GDataRequestFactory).Timeout.MaxValue

thank you
```

Original comment by `acaz...@gmail.com` on 9 Jul 2008 at 2:23

**Comment by GoogleCodeExporter** [comment]
```
I am reporting the same issue.  It seems that I receive this value any videos 
that 
are above the 100 Meg range.  I have specified a TimeOut and KeepAlive and 
everything else that I can think of.  I really need some help.  Is is possible 
there 
is an issue in the .NET library that is preventing files above 100 Meg via the 
direct upload method?
```

Original comment by `beemd...@gmail.com` on 1 Oct 2009 at 6:47

**Comment by GoogleCodeExporter** [comment]
```
((GDataRequestFactory)request.Service.RequestFactory).Timeout = 9999999;

This works

Thanks!!!
```

Original comment by `ues.sys...@gmail.com` on 20 Feb 2011 at 3:33
